version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fiGARhOKCvylUtemfLFSvzIIPlMsLauD
      MYSQL_DATABASE: railway
    ports:
      - "19967:19967"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: loja_ch
